xroad:
  instance: <FILL>

networking:
  # Fetch rows from database in batches of configured size.
  # This allows to optimize memory consuption and avoid loading big datasets into memory.
  # Optional parameter, default size is 100000.
  fetchsize: 100000

  # Time period to be included in the visualisation as number of days back from the most recent request-in date.
  interval: 30

  # Time period to be excluded from the visualization as number of days back from the most recent request-in date.
  # This allows collector and corrector to finish processing before publishing results.
  buffer: 10

  # X-Road service names that are treated as meta-services
  metaservices:
    - "getWsdl"
    - "listMethods"
    - "allowedMethods"
    - "getSecurityServerMetrics"
    - "getSecurityServerOperationalData"
    - "getSecurityServerHealthData"

  # Optional descriptor file that can be used to specify localized names of X-Road subsystems etc. in json format.
  xroad-descriptor-file: /etc/xroad-metrics/networking/xroad-descriptor.json

postgres:
  host: localhost
  port: 5432
  username: <FILL>
  password: <FILL>

logger:
  log-path: /var/log/xroad-metrics/networking/logs
  heartbeat-path: /var/log/xroad-metrics/networking/heartbeat
